version: '3.8'

services:
  app-php8:
    build: .
    container_name: php8
    volumes:
      - ./src:/var/www/html
    ports:
      - "5055:80"
    depends_on:
      - app-db-mysql8
    environment:
      MYSQL_HOST: app-db-mysql8
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: users_db

  app-db-mysql8:
    image: mysql:8
    container_name: mysql8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: users_db
    volumes:
      - ./mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "5050:80"
    environment:
      PMA_HOST: app-db-mysql8
    depends_on:
      - app-db-mysql8
